### ISSUE TITLE
Upgrade applause dependency when their Issue #11 is resolved

### ISSUE THREAD

**Issue by notmessenger** [outaTiME/broccoli-replace#10]
Once https://github.com/outaTiME/applause/issues/11 is resolved this repo's dependency on the `applause` dependency should be upgraded to address the

> coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

deprecation.

**Comment by outaTiME** [comment]
Sorry, finally after so much time I updated the dependencies in the new version of this plugin to fix the incompatibility and vulnerabilities problems.
