### ISSUE TITLE
Uprgade applause package that has high vulnerability or switch to alternative

### ISSUE THREAD

**Issue by dzbo** [outaTiME/broccoli-replace#11]
Current `applause` package contains ["Prototype Pollution" vulnerability](https://www.npmjs.com/advisories/782).

As I've noticed the package [doesn't seem to be maintained](https://github.com/outaTiME/applause/issues/17), there are already issues reported [without answer](https://github.com/outaTiME/applause/issues/15). For now I suggest to use alternative package as suggested [here](https://github.com/outaTiME/applause/issues/14#issuecomment-446203270) wdyt?

**Comment by outaTiME** [comment]
Sorry, finally after so much time I updated the dependencies in the new version of this plugin to fix the incompatibility and vulnerabilities problems.
