### ISSUE TITLE
Version 2.0.0+ modifies binary files

### ISSUE THREAD

**Issue by boris-petrov** [outaTiME/broccoli-replace#12]
I have the following code:

```js
new BroccoliReplace(new Funnel('node_modules/node-viewerjs/release', { destDir: '/ViewerJS' }), {
  files: ['**/*.js'],
  patterns: [{ match: /ODFViewerPlugin_css/, replacement: '""' }],
}),
```

The idea is that I want the files from `node_modules/node-viewerjs/release` copied in the release and then in the JS files this string to be replaced. There are also images in this directory which shouldn't be touched. This worked fine until version 2.0.0 (of course `new BroccoliReplace` was just `BroccoliReplace`). 2.0.0 and 2.0.1 modify the image files somehow.

Am I doing something wrong or is this a bug?

**Comment by outaTiME** [comment]
You could check again using the new version 2.0.2?

**Comment by boris-petrov** [comment]
@outaTiME - 2.0.2 resolves the issue! Thank you for the quick response and fix!
